### ISSUE TITLE
Useless code

### ISSUE THREAD

**Issue by seishin77** [sroze/PHP-Voronoi-algorithm#12]
Hi,

What is the purpose of this line?
It doesn't do anything effective, does it?

https://github.com/sroze/PHP-Voronoi-algorithm/blob/fb9b1b9b1daabef9e4d918eb1ed899138ba41458/src/Nurbs/Cell.php#L15

**Comment by sroze** [comment]
You are correct, it does not seem to be useful 😅 Do you want to PR a "fix"?

**Comment by sroze** [comment]
Fixed in 8ace5ee.
