### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by colorvamp** [sroze/PHP-Voronoi-algorithm#13]
https://github.com/sroze/PHP-Voronoi-algorithm/blob/8d142010cb3a4cca0259ce9777ef04c3a4fbdc8e/src/Nurbs/Delaunay.php#L33

Is this a typo? dont you mean "$point->x" instead of "$point->z"?

Thanks

**Comment by sroze** [comment]
Great spot!

**Comment by sroze** [comment]
Fixed in 9dca2c3.
